core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('university.urls', namespace='home')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/university/urls.py
from django.urls import path
from .views import home, university_dtl, fast_search, searcher, searcher_res, features, team

app_name = 'university'
urlpatterns = [
    path('', home, name='home'),
    path('details/<int:pk>', university_dtl, name='details'),
    path('fast-search/', fast_search, name='fast-search'),
    path('searcher/', searcher, name='searcher'),
    path('searcher-result/', searcher_res, name='searcher-res'),
    path('features/', features, name='features'),
    path('team', team, name='team'),
]

core/university/models.py
from django.db import models
from django.urls import reverse


def upload_img(instance, filename):
    return 'university_img/{0}/{1}'.format(instance.university.title, filename)


class University(models.Model):
    title = models.CharField(max_length=200)
    headnote = models.CharField(max_length=200)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('university:details', kwargs={'pk': self.pk})


class Degree(models.Model):
    university = models.ForeignKey('University', on_delete=models.CASCADE, related_name='degrees')
    qualifications = models.CharField(max_length=50)
    information = models.TextField()


class Faculty(models.Model):
    degree = models.ForeignKey('Degree', on_delete=models.CASCADE, related_name='faculties')
    title = models.CharField(max_length=100)
    LANGUAGES_CHOICES = (('KG', 'Kyrgyz'), ('RU', 'Russian'), ('EN', 'English'), ('TU', 'Turkish'))
    language = models.CharField(max_length=2, choices=LANGUAGES_CHOICES, default='Russian')
    description = models.TextField()
    duration = models.IntegerField(default=4)
    fee = models.IntegerField()
    aid = models.BooleanField(default=True)
    scholarship = models.BooleanField(default=False)


class FinanceAid(models.Model):
    university = models.ForeignKey('University', on_delete=models.CASCADE, related_name='aid')
    title = models.CharField(max_length=100, default='Finance aid information')
    description = models.TextField()


class FAQ(models.Model):
    university = models.ForeignKey('University', on_delete=models.CASCADE, related_name='faq')
    title = models.CharField(max_length=100, default='Frequently asked Question')
    description = models.TextField()


class Scholarship(models.Model):
    university = models.ForeignKey('University', on_delete=models.CASCADE, related_name='scholarship')
    title = models.CharField(max_length=100, default='Scholarship information')
    description = models.TextField() 


class Gallery(models.Model):
    university = models.ForeignKey('University', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=upload_img)

core/university/views.py
from django.shortcuts import render, redirect
from .models import University, Degree, Faculty


def home(request):
    universities = University.objects.all()
    return render(request, 'university/home.html', {'universities': universities})


def university_dtl(request, pk):
    university = University.objects.get(id=pk)
    return render(request, 'university/details.html', {'university': university})


def fast_search(request):
    search_req = request.GET.get('search')
    search_univ = search_req
    if search_req == '':
        return redirect('university:home')
    elif search_req:
        search_univ = University.objects.filter(title__icontains=search_req)
    return render(request, 'university/search_res.html', {'search_univ': search_univ, 'search_req': search_req})


def searcher(request):
    return render(request, 'university/searcher.html',)


def searcher_res(request):
    search_req = request.GET.dict()
    degree = search_req.get('degree')
    faculty = search_req.get('faculty')
    language = search_req.get('language')
    basis = search_req.get('basis')
    aid = search_req.get('aid')
    scholarship = search_req.get('scholarship')
    if basis == 'budget':
        fee = 0
        search_req['fee'] = 0
    else:
        fee = search_req.get('fee')
    if scholarship is None:
        scholarship = False
    if aid is None:
        aid = False
    f_id = Faculty.objects.filter(title__icontains=faculty, language__icontains=language[:2],
                                  fee__range=(1, fee), aid=aid, scholarship=scholarship).values_list('id', flat=True)
    search_univ = f_id
    if search_req == '':
        return redirect('university:home')
    elif search_req:
        search_univ = Degree.objects.filter(qualifications__icontains=degree, faculties__in=list(f_id))
    return render(request, 'university/search_res.html', {'searcher_res': search_univ, 'searcher_req': search_req})


def features(request):
    return render(request, 'features/soon.html')


def team(request):
    return render(request, 'about/team.html')

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
  <meta charset="UTF-8">
  <title>Main</title>
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all" />
  <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"> </script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand isoct font-weight-bolder" href="{% url 'university:home' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link isoct font-weight-bolder" href="{% url 'university:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0 rect" action="{% url 'university:fast-search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Fast search" aria-label="Search" name="search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<!--end navbar-->
{% block carousel %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner font-shadow">
    <div class="carousel-item active">
      <img src="{% static 'base/student2.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption mb-30">
        <h1 class="isoct font-weight-bold" >Choose the best for you</h1>
        <h3 class="azote font-weight-bold">You can find any university that is right for you</h3>
      </div>
        <div class="carousel-caption">
          <a href="{% url 'university:searcher' %}" role="button" class="btn btn-lg btn-outline-light rounded-pill rect">
            Search universities
          </a>
        </div>
    </div>

    <div class="carousel-item">
      <img src="{% static 'base/student1.png' %}" class="d-block w-100" alt="...">
        <div class="col-3 carousel-caption mb-30">
            <h1 class="isoct font-weight-bold">Enjoy studying </h1>
            <h3 class="azote font-weight-bold">Make the right choice to enjoy every day of study</h3>
        </div>
          <div class="carousel-caption">
          <a href="{% url 'university:searcher' %}" role="button" class="btn btn-lg btn-outline-light rounded-pill rect">
            Search universities
          </a>
        </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'base/student3.jpeg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block mb-5">
        <h1 class="isoct font-weight-bold">We will help determine</h1>
        <h3 class="azote font-weight-bold">Life presents many choices, the choices we make determine our future.</h3>
      </div>
        <div class="carousel-caption">
          <a href="{% url 'university:searcher' %}" role="button" class="btn btn-lg btn-outline-light rounded-pill rect">
            Search universities
          </a>
        </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!--end carousel-->
{% endblock %}

{% block content %}
{% endblock %}

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <small class="d-block mb-3 text-muted">© <span class="isoct font-weight-bolder">2020-2020</span></small>
    </div>
    <div class="col-6 col-md">
      <h5 class="isoct font-weight-bolder">Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="{% url 'university:features' %}">Cool stuff</a></li>
          <li><a class="text-muted" href="{% url 'university:features' %}">Random feature</a></li>
          <li><a class="text-muted" href="{% url 'university:features' %}">Team feature</a></li>
          <li><a class="text-muted" href="{% url 'university:features' %}">Stuff for developers</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
      <h5 class="isoct font-weight-bolder">Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="https://edu.gov.kg/ru/">Education</a></li>
          <li> <a class="text-muted" href="http://www.onlinewebfonts.com">Online web fonts</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
      <h5 class="isoct font-weight-bolder">About</h5>
      <ul class="list-unstyled text-small rect">
        <li><a class="text-muted" href="{% url 'university:team' %}">Team</a></li>
      </ul>
    </div>
  </div>
</footer>
</body>
</html>

core/university/templates/about/team.html
{% extends 'base.html' %}
{% load static %}

{% block carousel %}
{% endblock %}

{% block content %}

<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <hr>
            <h1 class="isoct mb-0">Our team</h1>
            <h5 class="text-muted">Project by:</h5>
            <hr>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-5 mb-5 mt-5 mr-5">
            <div class="card shadow">
                <img src="{% static 'base/team/eldiiar.jpg' %}" class="card-img-top" height="" alt="...">
                <div class="card-body">
                    <a href="https://github.com/eldiyar01" class="card-title isoct">
                        <h4 class="font-weight-bold">Eldiiar Abdyldaev</h4>
                    </a>
                    <p class="card-text rect text-muted">
                        University: AIU (Ala-Too)
                    </p>
                    <p class="card-text rect text-muted">Faculty: Computer Science</p>
                    <p class="card-text rect text-muted">Pretty simple boy</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted card-text">Life is like chess, I don't know how to play chess
                        <br>
                    <cite class="float-right">Maybe it's me</cite></small>
                </div>
            </div>
        </div>
        <div class="col-5 mb-5 mt-5 ml-5">
            <div class="card shadow">
                <img src="{% static 'base/team/elira.jpg' %}" class="card-img-top" height="473px" alt="...">
                <div class="card-body">
                    <a href="https://github.com/Libs-pixel" class="card-title isoct">
                        <h4 class="font-weight-bold">Akimbaeva Elira</h4>
                    </a>
                    <p class="card-text rect text-muted">
                        University: AIU (Ala-Too)
                    </p>
                    <p class="card-text rect text-muted">Faculty: Computer Science</p>
                    <p class="card-text rect text-muted">Pretty simple girl</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted card-text">Call me Libs
                        <br>
                    <cite class="float-right">Elira</cite></small>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/university/templates/features/soon.html
{% extends 'base.html' %}

{% block carousel %}
{% endblock %}

{% block content %}

<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <hr>
            <h1 class="isoct mb-0">We will add features soon </h1>
            <h5 class="text-muted">;)</h5>
            <hr>
        </div>
    </div>
</div>

{% endblock %}

core/university/templates/university/details.html
{% extends 'base.html' %}
{% load static %}

{% block carousel %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row mt-5 mb-4 ">
        <div class="col-12">
        <div class="card bg-dark text-white  border-secondary shadow-lg">
            <img src="{{ university.images.first.image.url }}" height="600px" class="card-img" alt="...">
            <div class="card-img-overlay">
                <h1 class="card-title isoct font-weight-bold font-shadow">{{ university.title }}</h1>
                <h4 class="card-text azote font-weight-bolder font-shadow">{{ university.headnote }}</h4>
            </div>
        </div>
        </div>
    </div>

    <div class="col-12 mb-4 shadow p-3 bg-white rounded">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="pills-ds-tab" data-toggle="pill" href="#pills-ds" role="tab"
                   aria-controls="pills-ds" aria-selected="true">
                    Description
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-dg-tab" data-toggle="pill" href="#pills-dg" role="tab"
                   aria-controls="pills-dg" aria-selected="false">
                    Degrees
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-fc-tab" data-toggle="pill" href="#pills-fc" role="tab"
                   aria-controls="pills-fc" aria-selected="false">
                    Faculties
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-ai-tab" data-toggle="pill" href="#pills-ai" role="tab"
                   aria-controls="pills-ai" aria-selected="false">
                    Finance aid
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-sc-tab" data-toggle="pill" href="#pills-sc" role="tab"
                   aria-controls="pills-fq" aria-selected="false">
                    Scholarship
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-fq-tab" data-toggle="pill" href="#pills-fq" role="tab"
                   aria-controls="pills-fq" aria-selected="false">
                    FAQ
                </a>
            </li>
        </ul>
        <hr>
        <div class="tab-content rect" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-ds" role="tabpanel" aria-labelledby="pills-ds-tab">
                <h2>{{ university.title }}</h2>
                <p>{{ university.description }}</p>
            </div>

            <div class="tab-pane fade" id="pills-dg" role="tabpanel" aria-labelledby="pills-dg-tab">
                <div class="accordion" id="accordion">
                {% for degree in university.degrees.all %}
                <div class="card">
                    <div class="card-header" id="hd{{ degree.id }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left text-dark" type="button" data-toggle="collapse"
                            data-target="#cl{{ degree.id }}" aria-expanded="true" aria-controls="cl{{ degree.id }}">
                            {{ degree.qualifications }}
                            </button>
                        </h2>
                    </div>
                    <div id="cl{{ degree.id }}" class="collapse"
                         aria-labelledby="hd{{ degree.id }}" data-parent="#accordion">
                        <div class="card-body">
                        {{ degree.information }}
                        </div>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>

            <div class="tab-pane fade" id="pills-fc" role="tabpanel" aria-labelledby="pills-fc-tab">
            {% for degree in university.degrees.all %}
                {% for faculty in degree.faculties.all %}
                    <div class="card">
                        <div class="card-header" id="hd{{ faculty.id }}">
                            <h2 class="mb-0">
                                <button class="btn btn-link btn-block text-left text-dark" type="button" data-toggle="collapse"
                                data-target="#cl{{ faculty.id }}" aria-expanded="true" aria-controls="cl{{ faculty.id }}">
                                    {{ faculty.title }}
                                </button>
                            </h2>
                        </div>
                        <div id="cl{{ faculty.id }}" class="collapse"
                             aria-labelledby="hd{{ faculty.id }}" data-parent="#accordion">
                            <div class="card-body">
                                <span class="font-weight-bold">Degree: </span>{{ faculty.degree.qualifications }}
                                <hr>
                                <span class="font-weight-bold">Language: </span>{{ faculty.get_language_display }}
                                <hr>
                                <span class="font-weight-bold">Duration: </span>{{ faculty.duration }} years
                                <hr>
                                <span class="font-weight-bold">Fee: </span>{{ faculty.fee }}$
                                <hr>
                                <span class="font-weight-bold">Aid: </span>{{ faculty.aid }}
                                <hr>
                                <span class="font-weight-bold">Scholarship: </span>{{ faculty.scholarship }}
                                <hr>
                                <span class="font-weight-bold">Description: </span>
                                <p> {{ faculty.description }}</p>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% endfor %}
            </div>


            <div class="tab-pane fade" id="pills-ai" role="tabpanel" aria-labelledby="pills-ai-tab">
                <h2>{{ university.aid.first.title }}</h2>
                {{ university.aid.first.description }}
            </div>
            
            <div class="tab-pane fade" id="pills-sc" role="tabpanel" aria-labelledby="pills-sc-tab">
                <h2>{{ university.scholarship.first.title }}</h2>
                {{ university.scholarship.first.description }}
            </div>

            <div class="tab-pane fade" id="pills-fq" role="tabpanel" aria-labelledby="pills-fq-tab">
                <h2>{{ university.faq.first.title }}</h2>
                {{ university.faq.first.description }}
            </div>
        </div>
    </div>

</div>

{% endblock %}

core/university/templates/university/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container mb-5 pt-5">
    <hr>
    <h2 class="isoct text-center"> ALL UNIVERSITIES </h2>
    <hr>
   <div class="row row-cols-1 row-cols-md-2 mt-5">
        {% for university in universities %}
            <div class="col mb-4">
                <div class="card shadow">
                    <img src="{{ university.images.first.image.url }}" class="card-img-top mh-29" alt="...">
                    <div class="card-body">
                        <h4 class="card-title isoct font-weight-bold">{{ university.title }}</h4>
                        <hr>
                        <p class="card-text">{{ university.headnote|slice:":150" }} ...</p>
                        <hr>
                        <div class="card-text">
                            <p>
                                <span class="rect">Degrees:</span>
                                {% for degree in university.degrees.all %}
                                    {{ degree.qualifications }},
                                {% endfor %}
                            </p>
                            <p>
                                <span class="rect">Finance Aid:</span>
                                {% if university.aid.first  %}
                                    Yes
                                {% else %}
                                    No
                                {% endif %}
                            </p>
                            <p>
                                <span class="rect">Scholarship:</span>
                                {% if university.scholarship.first %}
                                    Yes
                                {% else %}
                                    No
                                {% endif %}
                            </p>
                            <hr>
                        </div>
                        <a href="{{ university.get_absolute_url }}" role="button" class="btn btn-outline-dark ">Read</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/university/templates/university/search_res.html
{% extends 'base.html' %}
{% load static %}

{% block carousel %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row p-3 mt-4 mb-5">
            {% if search_req %}
                <div class="col-12 shadow p-3 mb-5">
                    <h3 class="rect"><strong>Results for:</strong> '{{ search_req }}'</h3>
            {% elif search_req != None %}
                    <h3>Nothing founded for '{{ search_req }}'</h3>
                </div>
            {% endif %}
            {% if search_univ %}
            {% for university in search_univ %}
                <div class="col-4 mb-4">
                    <div class="card shadow">
                        <img src="{{ university.images.first.image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ university.title }}</h5>
                            <p class="card-text">{{ university.headnote|slice:":50" }}</p>
                            <a href="{{ university.get_absolute_url }}" role="button" class="btn btn-outline-primary">Read</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endif %}
        </div>
        {% if searcher_req %}
            <div class="col-12 shadow p-3 mb-5">
            <h3 class="rect"><strong>Results for:</strong></h3>
                <hr>
                <h5>
                {% for x,y in searcher_req.items %}
                    <span class="font-weight-bold rect">{{x.title}}:</span>
                    {% if y != '' %}
                        {{y}},
                    {% else %}
                        any,
                    {% endif %}
                {% endfor %}
                </h5>
            </div>
            {% elif searcher_req != None %}
            <h3 class="col-12 shadow p-3 mt-4 mb-5">Nothing founded for '{{ searcher_req }}'</h3>
        {% endif %}
        {% if searcher_res %}
        {% for res in searcher_res %}
            <div class="col-4 mb-4">
                <div class="card shadow">
                    <img src="{{ res.university.images.first.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ res.university.title }}</h5>
                        <p class="card-text">{{ res.university.headnote|slice:":50" }}</p>
                        <a href="{{ res.university.get_absolute_url }}" role="button" class="btn btn-outline-primary">Read</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>


{% endblock %}

core/university/templates/university/searcher.html
{% extends 'base.html' %}
{% load static %}

{% block carousel %}
{% endblock %}

{% block content %}
<div class="container rect">
  <div class="py-5 text-center">
    <h2>Search form</h2>
    <p class="lead">Searching form by requirements to choose the best university for you</p>
    <p>Please try to fill all fields and checkboxes</p>
  </div>

  <div class="row justify-content-center">

    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Choose your requirements</h4>
      <form class="needs-validation" method="get" action="{% url 'university:searcher-res' %}">
        <div class="row">
          <div class="col-md-3 mb-3">
            <label for="degree">Degree</label>
            <select class="custom-select d-block w-100" id="degree" name="degree">
                <option value="">Choose...</option>
                <option value="bachelor">Bachelor</option>
                <option value="master">Master's degree</option>
                <option value="high">high school</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid degree.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="faculty">Faculty</label>
            <select class="custom-select d-block w-100" id="faculty" name="faculty">
              <option value="">Choose...</option>
              <option>Computer science</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid faculty.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="language">Language</label>
            <select class="custom-select d-block w-100" id="language" name="language">
              <option value="">Choose...</option>
                <option>Kyrgyz</option>
                <option>Russian</option>
                <option>English</option>
                <option>Turkish</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid language.
            </div>
          </div>
        </div>
        <div class="form-check">
            <div class="accordion" id="accordion">
                <div id="headingOne">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="basis" id="budget" value="budget"
                               data-toggle="collapse" data-target="#co" aria-expanded="true" aria-controls="co" checked>
                        <label class="form-check-label" for="budget">Budget</label>
                    </div>
                </div>
                <div id="co" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion"></div>

                <div id="headingTwo">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="basis" id="contract" value="contract"
                               data-toggle="collapse" data-target="#ct" aria-expanded="false" aria-controls="ct">
                        <label class="form-check-label" for="contract">Contract</label>
                    </div>
                </div>
                <div id="ct" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                    <div class="mt-3">
                        <label for="fee_range">Fee</label>
                        <div class="d-flex">
                          <div class="w-100">
                            <input type="range" name="fee" value="0" class="custom-range" id="fee_range" min="0"
                                   max="8000" step="10">
                          </div>
                          <span class="font-weight-bold text-primary ml-2 valueSpan2"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
          <hr class="mb-4">
        <small class="text-muted">Most universities provide financial support and scholarships </small>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="aid" name="aid" value="True">
          <label class="custom-control-label" for="aid">FinanceAid</label>
        </div>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="scholarship" name="scholarship" value="True">
          <label class="custom-control-label" for="scholarship">Scholarship</label>
        </div>
        <hr class="mb-4">

        <button class="btn btn-dark btn-lg btn-block" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {

  const $valueSpan = $('.valueSpan2');
  const $value = $('#fee_range');
  $valueSpan.html($value.val());
  $value.on('input change', () => {

    $valueSpan.html($value.val());
  });
});
</script>
{% endblock %}